apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitbit.fullname" . }}
  labels:
    {{- include "jitbit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jitbit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: jitbit-irsa
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
          # APP_URL
          {{- with (first .Values.ingress.hosts) }}
          - name: APP_URL
            value: {{ print "https://" .host "/" | quote }}
          {{- end }}
          # DB connection string
          - name: ConnectionStrings__DBConnectionString
            valueFrom:
              secretKeyRef:
                name: db-connection-string
                key: db-connection-string
          # S3 connectivity information
          - name: AttachmentsS3Bucket
            valueFrom:
              secretKeyRef:
                name: s3-bucket-jitbit-app-files-output 
                key: bucket_name
          - name: AttachmentsS3Login
            valueFrom:
              secretKeyRef:
                name: s3-bucket-jitbit-app-files-output 
                key: access_key_id
          - name: AttachmentsS3Password
            valueFrom:
              secretKeyRef:
                name: s3-bucket-jitbit-app-files-output 
                key: secret_access_key
          - name: AttachmentsS3Region
            value: eu-west-2
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
