name: image-build-push
on:
  push

jobs:
  image-build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'ecr_push')
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Jitbit app repo
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: BumpVersionAndPushTag
        uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: minor # Making this default visible
          INITIAL_VERSION: 0.0.0 # Making this default visible
          TAG_CONTEXT: repo # Making this default visible
          DRY_RUN: true
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ github.ref_name }} # Branch name

      - name: Pull down S3 app files
        run: aws s3 cp s3://${{ secrets.AMI_BUCKET_NAME }}/delius-jitbit/app docker/app  --recursive

      - name: Docker build
        run: docker build --no-cache -t ${{ secrets.CORE_SHARED_SERVICES_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/delius-jitbit-ecr-repo:${{ steps.BumpVersionAndPushTag.outputs.new_tag }} ./docker

      - name: Docker login
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.CORE_SHARED_SERVICES_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Docker push
        run: docker push ${{ secrets.CORE_SHARED_SERVICES_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/delius-jitbit-ecr-repo:${{ steps.BumpVersionAndPushTag.outputs.new_tag }}

      - name: Update task definition
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition delius-jitbit-task-definition)
          echo $TASK_DEFINITION | jq ".taskDefinition.containerDefinitions[0].image = \"${{ secrets.CORE_SHARED_SERVICES_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/delius-jitbit-ecr-repo:${{ steps.BumpVersionAndPushTag.outputs.new_tag }}\" | .taskDefinition | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)" >new_task_def.json
          aws ecs register-task-definition --family delius-jitbit-task-definition --cli-input-json file://new_task_def.json
          aws ecs update-service --cluster delius-jitbit --service delius-jitbit-ecs-service --force-new-deployment
