name: image-build-push
on:
  push:
    branches: [image_build_action]

#permissions:
#  contents: read???

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
        #- name: Pull down S3 app files
        #uses: actions/
      - name: Checkout Jitbit app repo
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Docker build
        run: docker build docker
        #- name: Tag docker file
        #- name: Push to core-shared-services ECR
        #- name: Update task definition
