name: Modernisation Platform Restart Service
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to restart Jitbit in'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - test
        - preproduction
        - production
jobs:
  restart-jitbit:
    name: Restart Jitbit - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      SERVICE_TASK_NAME: hmpps-${{ inputs.environment }}-delius-jitbit
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
          aws-region: "eu-west-2"

      - name: Restart Jitbit
        run: |
          aws ecs update-service --force-new-deployment --service ${{ env.SERVICE_TASK_NAME }} --cluster ${{ env.SERVICE_TASK_NAME }}
      
      - name: Ensure service stable
        run: |
          aws ecs wait services-stable --services ${{ env.SERVICE_TASK_NAME }} --cluster ${{ env.SERVICE_TASK_NAME }}
