name: Change RDS auto scaling tag
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - "development"
          - "test"
          - "preproduction"
      scaling-type:
        type: choice
        options:
            - "default" # - Automatically stop the instance overnight and start it in the morning. Absence of the instance-scheduling tag will have the same effect.
            - "skip-scheduling" # - Skip auto scheduling for the instance
            # - "skip-auto-start" #- Stop the instance at night, but skip starting it in the morning. This could be useful for the instances we want to make sure are automatically stopped every night, but we are happy to manually start when needed.
            # - "skip-auto-stop" # - Start the instance in the morning, but skip stopping it at night.

            # see https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/instance-scheduling.html#instance-scheduling-automatically-stop-non-production-instances-overnight

jobs:
    change-rds-tag:
        permissions:
          id-token: write
        runs-on: ubuntu-latest
        steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4 
          with:
            role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
            role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
            aws-region: "eu-west-2"

        - name: Set new tag on RDS instance
          run: |
            aws rds add-tags-to-resource \  --resource-name arn:aws:rds:eu-west-2:${{ vars.AWS_ACCOUNT_ID }}:db:delius-jitbit-${{ github.event.inputs.environment }}-database \
            --tags instance-scheduling=${{ github.event.inputs.scaling-type }}
