name: Disable Bastion scaling
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to scale bastion in'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - test
        - preproduction
        - production
jobs:
  scale-bastion:
    name: Bastion scale temp adjustment in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
        id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
          aws-region: "eu-west-2"

      - name: Scale auto scaling group
        run: |
          aws autoscaling set-desired-capacity --auto-scaling-group-name bastion_linux_daily --desired-capacity 1
          aws autoscaling put-scheduled-update-group-action --scheduled-action-name bastion_linux_scale_down  --auto-scaling-group-name bastion_linux_daily --max-size 1 --min-size 1 --desired-capacity 1 --recurrence "0 21 * * *"

      - name: Wait for bastion to scale
        run: |
            aws autoscaling wait instance-in-service --auto-scaling-group-name bastion_linux_daily
          
