name: Modernisation Platform Restart Service
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to scale bastion in'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - test
        - preproduction
        - production
jobs:
  restart-jitbit:
    name: Restart Jitbit - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Scale auto scaling group
        run: |
          aws autoscaling set-desired-capacity --auto-scaling-group-name bastion_linux_daily --desired-capacity 1

      - name: Wait for bastion to scale
        run: |
            aws autoscaling wait instance-in-service --auto-scaling-group-name bastion_linux_daily
          