name: Scale Jitbit ECS Service down
on:
  schedule:
    - cron:  '0 20 * * 1-5' # every weekday at 9pm BST, 8pm UTC

# use matrix to run the same job for multiple environments
jobs:
  scale-down-ecs-env:
    runs-on: ubuntu-latest
    name: Scale down ECS service
    strategy:
      matrix:
        environment: ["development", "test", "preproduction"]
    steps:
      - name: Scale down ECS service
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
          environment: ${{ matrix.environment }}
          action: down