name: Scale Jitbit ECS Service up in environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
      action:
        type: string

jobs:
    scale:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
        steps:
        - name: Calculate desired count
          run: |
            if [ "${{ github.event.inputs.action }}" = "up" ]; then
              echo DESIRED_COUNT="1" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.action }}" = "down" ]; then
              echo DESIRED_COUNT="0" >> $GITHUB_ENV
            fi

        - name: Scale Jitbit ECS Service
          run: |
            aws ecs update-service --cluster hmpps-${{ github.event.inputs.environment }}-delius-jitbit --service hmpps-${{ github.event.inputs.environment }}-delius-jitbit --desired-count ${{ github.env.DESIRED_COUNT }} --region eu-west-2

        - name: Wait for Jitbit to scale
          run: |
            aws ecs wait services-stable --cluster hmpps-${{ github.event.inputs.environment }}-delius-jitbit --service hmpps-${{ github.event.inputs.environment }}-delius-jitbit --region eu-west-2