name: Scale Jitbit ECS Service in environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
      action:
        type: string

jobs:
    auto-approve:
      runs-on: ubuntu-latest
      steps:
        - name: Generate token
          id: generate_token
          uses: tibdex/github-app-token@v2.1.0
          with:
            app_id: ${{ secrets.HMPPS_BOT_APP_ID }}
            private_key: ${{ secrets.HMPPS_BOT_PRIVATE_KEY }}
        
        - name: Get github environment ID from name via api
          run: |
            echo ENV_ID=$(curl -L \
            -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ministryofjustice/hmpps-cr-ancillary-jitbit-app/environments \
            | jq -r --arg ENVIRONMENT_NAME "${{ inputs.environment }}" '.[] | select(.name == $ENVIRONMENT_NAME) | .id') >> $GITHUB_ENV

        - name: Approve this deployment
          run: | 
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/ministryofjustice/hmpps-cr-ancillary-jitbit-app/actions/runs/${{github.run_id}}/pending_deployments \
                -d '{"environment_ids":["${{ env.ENV_ID }}"],"state":"approved","comment":"Pre-approved action..."}'
    scale:
        permissions:
          id-token: write
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
        - name: Ensure non production environment
          run: |
            if [ "${{ inputs.environment }}" = "production" ]; then
              echo "Production environment cannot be scaled"
              exit 1
            fi

        - name: Calculate desired count
          run: |
            if [ "${{ inputs.action }}" = "up" ]; then
              echo DESIRED_COUNT="1" >> $GITHUB_ENV
            elif [ "${{ inputs.action }}" = "down" ]; then
              echo DESIRED_COUNT="0" >> $GITHUB_ENV
            fi

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4 
          with:
            role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
            role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
            aws-region: "eu-west-2"

        - name: Get scaling state tag value
          id: scaling_state
          run: |
            scaling_state=$(aws ecs list-tags-for-resource --resource-arn arn:aws:ecs:eu-west-2:${{ vars.AWS_ACCOUNT_ID }}:service/hmpps-${{ inputs.environment }}-delius-jitbit/hmpps-${{ inputs.environment }}-delius-jitbit | jq -rc '.tags[] | select(.key == "scaling_state").value')

            echo "Scaling state is $scaling_state"
            echo "SCALING_STATE=$scaling_state" >> $GITHUB_OUTPUT

        - name: Scale Jitbit ECS Service
        # if scaling state is enabled, then scale
          if: ${{ steps.scaling_state.outputs.SCALING_STATE == 'enabled' }}
          run: |
            aws ecs update-service --cluster hmpps-${{ inputs.environment }}-delius-jitbit --service hmpps-${{ inputs.environment }}-delius-jitbit --desired-count ${{ env.DESIRED_COUNT }} --region eu-west-2

        - name: Wait for Jitbit to scale
          if: ${{ steps.scaling_state.outputs.SCALING_STATE == 'enabled' && inputs.action == 'up' }}
          run: |
            aws ecs wait services-stable --cluster hmpps-${{ inputs.environment }}-delius-jitbit --service hmpps-${{ inputs.environment }}-delius-jitbit --region eu-west-2
