name: Scale Jitbit ECS Service up in environment
on:
  schedule:
    - cron:  '0 21 * * 1-5' # every weekday at 9pm
jobs:
    # trigger the workflow in 'scale-up-ecs-env.yml'
    scale-down-dev:
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
            environment: development
            action: down
    # add more if needed
