name: Scale Jitbit ECS Service up in environment
on:
  schedule:
    - cron:  '0 6 * * 1-5' # every weekday at 6am

jobs:
    # trigger the workflow in 'scale-up-ecs-env.yml'
    scale-up-dev:
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
            environment: development
            action: up
        secrets: inherit
    # add more if needed
