name: Scale Jitbit ECS Service in environment
on:
  workflow_call:
    inputs:
      environment:
        type: string
      action:
        type: string

jobs:
    scale:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
        steps:
        - name: Ensure non production environment
          run: |
            if [ "${{ github.event.inputs.environment }}" = "production" ]; then
              echo "Production environment cannot be scaled"
              exit 1
            fi

        - name: Calculate desired count
          run: |
            if [ "${{ github.event.inputs.action }}" = "up" ]; then
              echo DESIRED_COUNT="1" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.action }}" = "down" ]; then
              echo DESIRED_COUNT="0" >> $GITHUB_ENV
            fi

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4 
          with:
            role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
            role-session-name: githubactionsrolesession
            aws-region: "eu-west-2"

        - name: Scale Jitbit ECS Service
          run: |
            aws ecs update-service --cluster hmpps-${{ github.event.inputs.environment }}-delius-jitbit --service hmpps-${{ github.event.inputs.environment }}-delius-jitbit --desired-count ${{ github.env.DESIRED_COUNT }} --region eu-west-2

        - name: Wait for Jitbit to scale
          run: |
            aws ecs wait services-stable --cluster hmpps-${{ github.event.inputs.environment }}-delius-jitbit --service hmpps-${{ github.event.inputs.environment }}-delius-jitbit --region eu-west-2
