name: Scale Jitbit ECS Service up
on:
  schedule:
    - cron:  '0 5 * * 1-5' # every weekday at 6am BST, 5am UTC

jobs:
    # trigger the workflow in 'scale-up-ecs-env.yml'
    scale-up-dev:
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
            environment: development
            action: up
        secrets: inherit
    scale-up-test:
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
            environment: test
            action: up
        secrets: inherit
    scale-up-preproduction:
        uses: ./.github/workflows/scale-ecs-env.yml
        with:
            environment: preproduction
            action: up
        secrets: inherit
    # add more if needed
