name: Scale Jitbit ECS Service down
on:
  schedule:
    - cron:  '30 23 * * 1-5' # every weekday at 9pm BST, 8pm UTC

# use matrix to run the same job for multiple environments
jobs:
  scale-down-ecs-env:
    strategy:
      matrix:
        environment: ["development"]
#        environment: ["development", "test", "preproduction"]
    uses: ./.github/workflows/scale-ecs-env.yml
    with:
        environment: ${{ matrix.environment }}
        action: down
          