name: Remove entries from SES Suppression List
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to remove suppression from"
        type: choice
        required: true
        options:
          - development
          - test
          - preproduction
          - production
      emails:
        description: "Email addresses to remove (comma separated for multiple)"
        type: string
        required: true
  workflow_call:
    inputs:
      environment:
        description: "Environment to remove suppression from"
        type: string
        required: true
      emails:
        description: "Email addresses to remove (comma separated for multiple)"
        type: string
        required: true

jobs:
  remove-from-suppression:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "hmpps-cr-ancillary-jitbit-app-${{ github.run_number }}"
          aws-region: "eu-west-2"

      - name: Remove emails from suppression list
        id: remove_emails
        run: |
          # Initialize counter for removed emails
          removed_count=0
          removed_emails=""

          # Split comma-separated emails and remove whitespace
          emails=($(echo "${{ inputs.emails }}" | tr ',' '\n' | sed 's/^ *//g' | sed 's/ *$//g'))

          for email in "${emails[@]}"; do
            echo "Checking if $email is in suppression list..."
            
            # Try to get the suppression attributes for the email
            if aws sesv2 get-suppressed-destination --email-address "$email" >/dev/null 2>&1; then
              echo "Found $email in suppression list, removing..."
              aws sesv2 delete-suppressed-destination --email-address "$email"
              
              if [ $? -eq 0 ]; then
                echo "✅ Successfully removed $email"
                removed_count=$((removed_count + 1))
                removed_emails="${removed_emails}${email}\n"
              else
                echo "❌ Failed to remove $email"
                exit 1
              fi
            else
              echo "ℹ️ $email is not in the suppression list for ${{ inputs.environment }}"
            fi
          done

          # Set outputs for use in subsequent steps
          echo "removed_count=${removed_count}" >> $GITHUB_OUTPUT
          echo "removed_emails<<EOF" >> $GITHUB_OUTPUT
          echo -e "${removed_emails}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Alert Slack - Failure
        if: failure()
        run: |
          curl --silent -X POST -H 'Content-type: application/json' --data '{
            "blocks":[
              {
                "type":"header",
                "text":{"type":"plain_text","text":":fail: SES Suppression List Update Failed"}
              },
              {
                "type":"divider"
              },
              {
                "type":"section",
                "text":{
                  "type":"mrkdwn",
                  "text":"Failed to remove email(s) from suppression list in ${{ inputs.environment }} environment"
                },
                "accessory": {
                  "type": "button",
                  "text": {"type": "plain_text","text": ":github: View Job","emoji": true},
                  "url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "action_id": "button-action"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Alert Slack - Success
        if: success() && steps.remove_emails.outputs.removed_count > 0
        run: |
          curl --silent -X POST -H 'Content-type: application/json' --data '{
            "blocks":[
              {
                "type":"header",
                "text":{"type":"plain_text","text":":white_check_mark: SES Suppression List Updated"}
              },
              {
                "type":"divider"
              },
              {
                "type":"section",
                "text":{
                  "type":"mrkdwn",
                  "text":"Successfully removed ${{ steps.remove_emails.outputs.removed_count }} email(s) from ${{ inputs.environment }} suppression list:\n${{ steps.remove_emails.outputs.removed_emails }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {"type": "plain_text","text": ":github: View Job","emoji": true},
                  "url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "action_id": "button-action"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
